### ISSUE TITLE
TypeError e.select is not a function

### ISSUE THREAD

**Issue by productdevbook** [better-auth/better-auth#734]
Singin or Singup this problem.

```
[Better Auth]  ERROR   TypeError e.select is not a function

  at Object.findOne (node_modules/.pnpm/better-auth@1.0.8/node_modules/better-auth/dist/adapters/drizzle.js:1:9649)
  at Object.findUserByEmail (node_modules/.pnpm/better-auth@1.0.8/node_modules/better-auth/dist/index.js:83:17800)
  at node_modules/.pnpm/better-auth@1.0.8/node_modules/better-auth/dist/index.js:3:6564
  at handle (node_modules/.pnpm/better-call@0.3.3-beta.2/node_modules/better-call/src/endpoint.ts:175:21)
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  at async Te.a.<computed> (node_modules/.pnpm/better-auth@1.0.8/node_modules/better-auth/dist/index.js:83:9257)
  at async handler (node_modules/.pnpm/better-call@0.3.3-beta.2/node_modules/better-call/src/router.ts:116:23)
  at async handler (node_modules/.pnpm/better-call@0.3.3-beta.2/node_modules/better-call/src/router.ts:167:16)
  at async node_modules/.pnpm/h3@1.13.0/node_modules/h3/dist/index.mjs:1978:19
  at async Object.callAsync (node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:72:16)

```

**Comment by Bekacru** [comment]
are you sure you're properly passing your drizzle db to the adapter?

**Comment by productdevbook** [comment]
You're right, it's my fault. It's working now. Thank you. :heart:
