### ISSUE TITLE
Fetch Requests Don't Retry on Network Failure (need exponential backoff algorithm)

### ISSUE THREAD

**Issue by daveycodez** [better-auth/better-auth#987]
### Is this suited for github?

- [X] Yes, this is suited for github

### To Reproduce

If the user is on mobile using a static application (e.g. Capacitor), the auth API is hosted on a production server. If the user's connection drops briefly when trying to fetch /api/auth/get-session, it will fail. There is currently no mechanism to retry fetching the session. This appears to the end user as if they've logged out, and they must refresh (hope the app has a built in way to do a full page refresh). They will have to quit the app or PWA and re-open it entirely, or try to log back in. Navigating the app won't attempt to refresh the session. At this point it's important that it retries and isPending is still set to true.

This may happen for anyone whose connection drops when trying to get session on any browser, but that is the easiest example where it will occur often, mobile connections drop all the time and if the user opens the static app they shouldn't think they've been logged out. The expected behavior is that they see spinners, Skeletons or stale data.

[SWR](https://swr.vercel.app/) manages this by using the [exponential backoff algorithm](https://en.wikipedia.org/wiki/Exponential_backoff)

You can see from their docs here: https://swr.vercel.app/docs/error-handling

My suggestion is one of the following -

1. Use SWR for all fetch requests in the authClient (would also allow us to use our own SWRConfig)
2. Allow us to override the default fetcher in the auth-client configuration
3. Use a custom fetchWithRetry function

If C. here is my function that also supports "X-RateLimit-Reset" header. It defaults to exponential backoff method, waiting 5 seconds before the first retry. I do think this should be baked in to the auth client itself somehow, I think it will need to be a standard feature for get-session especially, but other requests may also benefit from this.

```ts
async function fetchWithRetry(
    url: string,
    options?: RequestInit,
    retryCount = 5,
    delay = 5000
) {
    const sleep = (ms: number): Promise<void> =>
        new Promise((resolve) => setTimeout(resolve, ms))

    let attempts = 0
    let waitTime = 0

    while (attempts < retryCount) {
        attempts++

        try {
            const response = await fetch(url, options)

            // Check if response indicates rate limiting
            if (response.status === 429 && attempts < retryCount) {
                const resetTime = response.headers.get("X-RateLimit-Reset")

                if (resetTime) {
                    // Calculate time to wait based on the current time and the reset time
                    const currentTime = Math.floor(Date.now())
                    waitTime = (Number(resetTime) - currentTime)
                }
            } else {
                return response
            }
        } catch (error) {
            if (attempts >= retryCount) {
                throw error
            }
        }

        // Exponential backoff
        if (waitTime <= 0) {
            waitTime = delay * Math.pow(2, attempts)
        }

        await sleep(waitTime)
    }

    throw new Error("Max retries reached")
}
```

### Current vs. Expected behavior

Refetch get-session using exponential backoff algorithm when it fails due to network error or 429 rate limit response.

### What version of Better Auth are you using?

1.0.22

### Provide environment information

```bash
Next.js
```

### Which area(s) are affected? (Select all that apply)

Backend, Client

**Comment by Bekacru** [comment]
The Better Auth client is built on top of **Better Fetch**, which includes a retry mechanism with exponential backoff baked in (https://better-fetch.vercel.app/docs/timeout-and-retry). You can pass any options supported by Better Fetch via the `fetchOptions` when creating the client.  

But, `getSession` doesn't return an error if the session doesn't exist after it hits the db. it simply returns `null`. This behavior is intentional to avoid logging unnecessary errors, as it's likely the expected outcome in most cases.  

And for your sugesstions if needed, you can use a custom fetcher by passing `fetchOptions.customFetchImpl` to the `createAuthClient` function.

**Comment by daveycodez** [comment]
My biggest concern is a shaky connection hitting get-session then failing, we need to make sure that isPending is still set to true. In my testing it "logs out" the user because I use isPending to show Skeletons, if the network request fails, the skeletons go away and the logged out state gets rendered. I'll try the better fetch options but I think the retry on network failure while keeping isPending true should be the default

**Comment by Bekacru** [comment]
for network failures better fetch retries should work for most cases.

**Comment by daveycodez** [comment]
Hmm I tried this and it doesn't seem to be working

```ts
export const authClient = createAuthClient({
    baseURL: getURL(),
    plugins: [
        anonymousClient()
    ],
    fetchOptions: {
        retry: {
            count: 3,
            interval: 1000, //optional
            type: "exponential",
            attempts: 5,
            baseDelay: 1000, // Start with 1 second delay
            maxDelay: 10000 // Cap the delay at 10 seconds, so requests would go out after 1s then 2s, 4s, 8s, 10s
        }
    }
})
```

```shell
GET https://newtech.dev/api/auth/get-session?currentURL=http%3A%2F%2Flocalhost%3A3000%2F net::ERR_INTERNET_DISCONNECTED
T @ _app-faf126e708b066b2.js:1
await in T
(anonymous) @ _app-faf126e708b066b2.js:1
i @ _app-faf126e708b066b2.js:1
(anonymous) @ _app-faf126e708b066b2.js:1
(anonymous) @ _app-faf126e708b066b2.js:1
(anonymous) @ _app-faf126e708b066b2.js:1
(anonymous) @ _app-faf126e708b066b2.js:1
(anonymous) @ _app-faf126e708b066b2.js:1
get @ _app-faf126e708b066b2.js:1
(anonymous) @ _app-faf126e708b066b2.js:1
l.<computed> @ _app-faf126e708b066b2.js:1
oF @ _app-faf126e708b066b2.js:1
oW @ _app-faf126e708b066b2.js:1
lb @ framework-a4ddb9b21624b39b.js:1
aY @ framework-a4ddb9b21624b39b.js:1
ot @ framework-a4ddb9b21624b39b.js:1
ua @ framework-a4ddb9b21624b39b.js:1
(anonymous) @ framework-a4ddb9b21624b39b.js:1
ul @ framework-a4ddb9b21624b39b.js:1
i3 @ framework-a4ddb9b21624b39b.js:1
uT @ framework-a4ddb9b21624b39b.js:1
z @ framework-a4ddb9b21624b39b.js:1Understand this errorAI
_app-faf126e708b066b2.js:1 
        
        
       Uncaught (in promise) TypeError: Failed to fetch
    at T (_app-faf126e708b066b2.js:1:32507)
    at async _app-faf126e708b066b2.js:1:29640
```

I set my baseURL to production then turn off WiFi and the request fails immediately and doesn't retry, isPending goes to false and I get the logged out state. This means if a user on mobile opens the app during a connection drop (on a train or something) they will see a logged out state on app open, when ideally they would be seeing spinners from isPending still being true and it retrying on an interval and successfully getting in once that connection recovers

**Comment by daveycodez** [comment]
This could also happen on a shaky connection on a normal mobile site where the page loads but then the get-session fails, the user will have to refresh the entire page to fix it & be confused about why they are signed out.

I tried this option:

```ts
         shouldRetry: (response) => {
                console.log("shouldRetry")
                return true
            }
```

and shouldRetry is never getting called. Maybe fetchOptions aren't getting passed along properly to better-fetch

Using my custom fetchWithRetry function with customFetchImpl is working, but it would be great to pass options to better-fetch so I don't need the custom implementation. Or even better to have the defaults set to auto retry without needing to configure it

**Comment by daveycodez** [comment]
I think this is the culprit for isPending getting set to false prematurely:

https://github.com/better-auth/better-auth/blob/125b44d5c5eff403782a90c9ec1a42fb6df93195/packages/better-auth/src/client/query.ts#L52

```ts
async onRequest(context) {
		const currentValue = value.get();
		value.set({
			isPending: currentValue.data === null,
			data: currentValue.data,
			error: null,
			isRefetching: true,
		});
		await opts?.onRequest?.(context);
	},
```

Here isPending gets set to false onRequest because value is null on the initial request

**Comment by daveycodez** [comment]
I've determined that the options for retry are indeed correctly getting passed to betterFetch, and it is working for retrying requests with 429 or any other errors.. however... the most important thing to retry is Network Failure, but better-fetch itself does not support this. If there is a Network Error, better-fetch throws an error and does not retry.

```shell
index.js:553 
        
        
       Uncaught (in promise) TypeError: Failed to fetch
    at betterFetch (index.js:553:24)
    at async $fetch (index.js:262:12)
```

You can set catchAllError: true to catch this error to avoid the exception, but it won't retry. I've dug through their docs and I don't see any way to retry on fetch error being thrown, only on response errors

**Comment by daveycodez** [comment]
```ts
  fetchOptions: {
        customFetchImpl: async (input, init) => {
            try {
                return await fetch(input, init)
            } catch (error) {
                return Response.error()
            }
        },
        retry: {
            type: "exponential",
            attempts: 5,
            baseDelay: 1000, // Start with 1 second delay
            maxDelay: 10000 // Cap the delay at 10 seconds, so requests would go out after 1s then 2s, 4s, 8s, 10s
        },
    },
```

This is the custom fix I've tried to make better-fetch catch errors. This does work in that it will retry, but isPending flickers back and forth between true and false during each retry instead of just staying isPending true

**Comment by daveycodez** [comment]
the onError callback needs to be updated like this to prevent isPending flickering and support retries properly:

https://github.com/better-auth/better-auth/blob/125b44d5c5eff403782a90c9ec1a42fb6df93195/packages/better-auth/src/client/query.ts#L58

```ts
async onError(context) {
    const { request } = context
    const retry = request.retry as { attempts: number }
    const retryAttempt = request.retryAttempt || 0

    if (retry?.attempts && retryAttempt < retry.attempts) return

    value.set({
        error: context.error,
        data: null,
        isPending: false,
        isRefetching: false,
    })

    await opts?.onError?.(context)
}
```

And then this needs to be the default customFetchImpl:

```ts
customFetchImpl: async (input, init) => {
    try {
        return await fetch(input, init)
    } catch (error) {
        return Response.error()
    }
}
```

And ideally out of the box default retry settings for all GET requests (same delay SWR uses) -
```ts
retry: {
  shouldRetry: (response) => {
      if (response === null) return true
      if (response.type === "error") return true
      if (response.status === 429) return true

      return false
  },
  type: "exponential",
  attempts: Infinity,
  baseDelay: 5000,
  maxDelay: Infinity
}
```

**Comment by daveycodez** [comment]
@Bekacru possible to get the onError callback updated with the checks for retry attempts? That's the only blocker to being able to use retry on failure with better auth

https://github.com/better-auth/better-auth/blob/125b44d5c5eff403782a90c9ec1a42fb6df93195/packages/better-auth/src/client/query.ts#L58

```ts
async onError(context) {
    const { request } = context
    const retry = request.retry as { attempts: number }
    const retryAttempt = request.retryAttempt || 0

    if (retry?.attempts && retryAttempt < retry.attempts) return

    value.set({
        error: context.error,
        data: null,
        isPending: false,
        isRefetching: false,
    })

    await opts?.onError?.(context)
}
```

**Comment by Bekacru** [comment]
Hey @daveycodez, yeah, it will be added in the next release! but, for the default retry rule, we're going to avoid that since some people use the auth client with something like SWR or react query. This could lead to duplicate retry rules, and it's easy enough to configure it yourself if needed.

**Comment by Bekacru** [comment]
Response error is returned on network failures starting rom `1.1.7`

**Comment by daveycodez** [comment]
@Bekacru I see that fix looks great, but how about the fix for isPending flickering back and forth during retries? From the onError code above. isPending should remain true during retries

**Comment by yasseralsaidi** [comment]
My users say they face the same problem: 'network error' when trying to sign in :(
any fix?
